# coding: utf-8

"""
    vpc

    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CreateSubnetRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'region_code': 'str',
        'subnet_type_code': 'str',
        'usage_type_code': 'str',
        'network_acl_no': 'str',
        'subnet': 'str',
        'subnet_name': 'str',
        'vpc_no': 'str',
        'zone_code': 'str'
    }

    attribute_map = {
        'region_code': 'regionCode',
        'subnet_type_code': 'subnetTypeCode',
        'usage_type_code': 'usageTypeCode',
        'network_acl_no': 'networkAclNo',
        'subnet': 'subnet',
        'subnet_name': 'subnetName',
        'vpc_no': 'vpcNo',
        'zone_code': 'zoneCode'
    }

    def __init__(self, region_code=None, subnet_type_code=None, usage_type_code=None, network_acl_no=None, subnet=None, subnet_name=None, vpc_no=None, zone_code=None):  # noqa: E501
        """CreateSubnetRequest - a model defined in Swagger"""  # noqa: E501

        self._region_code = None
        self._subnet_type_code = None
        self._usage_type_code = None
        self._network_acl_no = None
        self._subnet = None
        self._subnet_name = None
        self._vpc_no = None
        self._zone_code = None
        self.discriminator = None

        if region_code is not None:
            self.region_code = region_code
        self.subnet_type_code = subnet_type_code
        if usage_type_code is not None:
            self.usage_type_code = usage_type_code
        self.network_acl_no = network_acl_no
        self.subnet = subnet
        if subnet_name is not None:
            self.subnet_name = subnet_name
        self.vpc_no = vpc_no
        self.zone_code = zone_code

    @property
    def region_code(self):
        """Gets the region_code of this CreateSubnetRequest.  # noqa: E501

        REGION코드  # noqa: E501

        :return: The region_code of this CreateSubnetRequest.  # noqa: E501
        :rtype: str
        """
        return self._region_code

    @region_code.setter
    def region_code(self, region_code):
        """Sets the region_code of this CreateSubnetRequest.

        REGION코드  # noqa: E501

        :param region_code: The region_code of this CreateSubnetRequest.  # noqa: E501
        :type: str
        """

        self._region_code = region_code

    @property
    def subnet_type_code(self):
        """Gets the subnet_type_code of this CreateSubnetRequest.  # noqa: E501

        서브넷유형코드  # noqa: E501

        :return: The subnet_type_code of this CreateSubnetRequest.  # noqa: E501
        :rtype: str
        """
        return self._subnet_type_code

    @subnet_type_code.setter
    def subnet_type_code(self, subnet_type_code):
        """Sets the subnet_type_code of this CreateSubnetRequest.

        서브넷유형코드  # noqa: E501

        :param subnet_type_code: The subnet_type_code of this CreateSubnetRequest.  # noqa: E501
        :type: str
        """
        if subnet_type_code is None:
            raise ValueError("Invalid value for `subnet_type_code`, must not be `None`")  # noqa: E501

        self._subnet_type_code = subnet_type_code

    @property
    def usage_type_code(self):
        """Gets the usage_type_code of this CreateSubnetRequest.  # noqa: E501

        용도유형코드  # noqa: E501

        :return: The usage_type_code of this CreateSubnetRequest.  # noqa: E501
        :rtype: str
        """
        return self._usage_type_code

    @usage_type_code.setter
    def usage_type_code(self, usage_type_code):
        """Sets the usage_type_code of this CreateSubnetRequest.

        용도유형코드  # noqa: E501

        :param usage_type_code: The usage_type_code of this CreateSubnetRequest.  # noqa: E501
        :type: str
        """

        self._usage_type_code = usage_type_code

    @property
    def network_acl_no(self):
        """Gets the network_acl_no of this CreateSubnetRequest.  # noqa: E501

        네트워크ACL번호  # noqa: E501

        :return: The network_acl_no of this CreateSubnetRequest.  # noqa: E501
        :rtype: str
        """
        return self._network_acl_no

    @network_acl_no.setter
    def network_acl_no(self, network_acl_no):
        """Sets the network_acl_no of this CreateSubnetRequest.

        네트워크ACL번호  # noqa: E501

        :param network_acl_no: The network_acl_no of this CreateSubnetRequest.  # noqa: E501
        :type: str
        """
        if network_acl_no is None:
            raise ValueError("Invalid value for `network_acl_no`, must not be `None`")  # noqa: E501

        self._network_acl_no = network_acl_no

    @property
    def subnet(self):
        """Gets the subnet of this CreateSubnetRequest.  # noqa: E501

        서브넷  # noqa: E501

        :return: The subnet of this CreateSubnetRequest.  # noqa: E501
        :rtype: str
        """
        return self._subnet

    @subnet.setter
    def subnet(self, subnet):
        """Sets the subnet of this CreateSubnetRequest.

        서브넷  # noqa: E501

        :param subnet: The subnet of this CreateSubnetRequest.  # noqa: E501
        :type: str
        """
        if subnet is None:
            raise ValueError("Invalid value for `subnet`, must not be `None`")  # noqa: E501

        self._subnet = subnet

    @property
    def subnet_name(self):
        """Gets the subnet_name of this CreateSubnetRequest.  # noqa: E501

        서브넷이름  # noqa: E501

        :return: The subnet_name of this CreateSubnetRequest.  # noqa: E501
        :rtype: str
        """
        return self._subnet_name

    @subnet_name.setter
    def subnet_name(self, subnet_name):
        """Sets the subnet_name of this CreateSubnetRequest.

        서브넷이름  # noqa: E501

        :param subnet_name: The subnet_name of this CreateSubnetRequest.  # noqa: E501
        :type: str
        """

        self._subnet_name = subnet_name

    @property
    def vpc_no(self):
        """Gets the vpc_no of this CreateSubnetRequest.  # noqa: E501

        VPC번호  # noqa: E501

        :return: The vpc_no of this CreateSubnetRequest.  # noqa: E501
        :rtype: str
        """
        return self._vpc_no

    @vpc_no.setter
    def vpc_no(self, vpc_no):
        """Sets the vpc_no of this CreateSubnetRequest.

        VPC번호  # noqa: E501

        :param vpc_no: The vpc_no of this CreateSubnetRequest.  # noqa: E501
        :type: str
        """
        if vpc_no is None:
            raise ValueError("Invalid value for `vpc_no`, must not be `None`")  # noqa: E501

        self._vpc_no = vpc_no

    @property
    def zone_code(self):
        """Gets the zone_code of this CreateSubnetRequest.  # noqa: E501

        ZONE코드  # noqa: E501

        :return: The zone_code of this CreateSubnetRequest.  # noqa: E501
        :rtype: str
        """
        return self._zone_code

    @zone_code.setter
    def zone_code(self, zone_code):
        """Sets the zone_code of this CreateSubnetRequest.

        ZONE코드  # noqa: E501

        :param zone_code: The zone_code of this CreateSubnetRequest.  # noqa: E501
        :type: str
        """
        if zone_code is None:
            raise ValueError("Invalid value for `zone_code`, must not be `None`")  # noqa: E501

        self._zone_code = zone_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateSubnetRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
