# coding: utf-8

"""
    vpc

    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RouteParameter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'destination_cidr_block': 'str',
        'target_type_code': 'str',
        'target_no': 'str',
        'target_name': 'str'
    }

    attribute_map = {
        'destination_cidr_block': 'destinationCidrBlock',
        'target_type_code': 'targetTypeCode',
        'target_no': 'targetNo',
        'target_name': 'targetName'
    }

    def __init__(self, destination_cidr_block=None, target_type_code=None, target_no=None, target_name=None):  # noqa: E501
        """RouteParameter - a model defined in Swagger"""  # noqa: E501

        self._destination_cidr_block = None
        self._target_type_code = None
        self._target_no = None
        self._target_name = None
        self.discriminator = None

        self.destination_cidr_block = destination_cidr_block
        self.target_type_code = target_type_code
        if target_no is not None:
            self.target_no = target_no
        if target_name is not None:
            self.target_name = target_name

    @property
    def destination_cidr_block(self):
        """Gets the destination_cidr_block of this RouteParameter.  # noqa: E501

        목적지CIDR블록  # noqa: E501

        :return: The destination_cidr_block of this RouteParameter.  # noqa: E501
        :rtype: str
        """
        return self._destination_cidr_block

    @destination_cidr_block.setter
    def destination_cidr_block(self, destination_cidr_block):
        """Sets the destination_cidr_block of this RouteParameter.

        목적지CIDR블록  # noqa: E501

        :param destination_cidr_block: The destination_cidr_block of this RouteParameter.  # noqa: E501
        :type: str
        """
        if destination_cidr_block is None:
            raise ValueError("Invalid value for `destination_cidr_block`, must not be `None`")  # noqa: E501

        self._destination_cidr_block = destination_cidr_block

    @property
    def target_type_code(self):
        """Gets the target_type_code of this RouteParameter.  # noqa: E501

        목적지유형코드  # noqa: E501

        :return: The target_type_code of this RouteParameter.  # noqa: E501
        :rtype: str
        """
        return self._target_type_code

    @target_type_code.setter
    def target_type_code(self, target_type_code):
        """Sets the target_type_code of this RouteParameter.

        목적지유형코드  # noqa: E501

        :param target_type_code: The target_type_code of this RouteParameter.  # noqa: E501
        :type: str
        """
        if target_type_code is None:
            raise ValueError("Invalid value for `target_type_code`, must not be `None`")  # noqa: E501

        self._target_type_code = target_type_code

    @property
    def target_no(self):
        """Gets the target_no of this RouteParameter.  # noqa: E501

        목적지번호  # noqa: E501

        :return: The target_no of this RouteParameter.  # noqa: E501
        :rtype: str
        """
        return self._target_no

    @target_no.setter
    def target_no(self, target_no):
        """Sets the target_no of this RouteParameter.

        목적지번호  # noqa: E501

        :param target_no: The target_no of this RouteParameter.  # noqa: E501
        :type: str
        """

        self._target_no = target_no

    @property
    def target_name(self):
        """Gets the target_name of this RouteParameter.  # noqa: E501

        목적지이름  # noqa: E501

        :return: The target_name of this RouteParameter.  # noqa: E501
        :rtype: str
        """
        return self._target_name

    @target_name.setter
    def target_name(self, target_name):
        """Sets the target_name of this RouteParameter.

        목적지이름  # noqa: E501

        :param target_name: The target_name of this RouteParameter.  # noqa: E501
        :type: str
        """

        self._target_name = target_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RouteParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
