# coding: utf-8

"""
    clouddb

    OpenAPI spec version: 2018-06-21T02:28:05Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CloudDBConfigGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'config_group_no': 'str',
        'config_group_type': 'str',
        'config_group_name': 'str'
    }

    attribute_map = {
        'config_group_no': 'configGroupNo',
        'config_group_type': 'configGroupType',
        'config_group_name': 'configGroupName'
    }

    def __init__(self, config_group_no=None, config_group_type=None, config_group_name=None):  # noqa: E501
        """CloudDBConfigGroup - a model defined in Swagger"""  # noqa: E501

        self._config_group_no = None
        self._config_group_type = None
        self._config_group_name = None
        self.discriminator = None

        if config_group_no is not None:
            self.config_group_no = config_group_no
        if config_group_type is not None:
            self.config_group_type = config_group_type
        if config_group_name is not None:
            self.config_group_name = config_group_name

    @property
    def config_group_no(self):
        """Gets the config_group_no of this CloudDBConfigGroup.  # noqa: E501

        설정그룹번호  # noqa: E501

        :return: The config_group_no of this CloudDBConfigGroup.  # noqa: E501
        :rtype: str
        """
        return self._config_group_no

    @config_group_no.setter
    def config_group_no(self, config_group_no):
        """Sets the config_group_no of this CloudDBConfigGroup.

        설정그룹번호  # noqa: E501

        :param config_group_no: The config_group_no of this CloudDBConfigGroup.  # noqa: E501
        :type: str
        """

        self._config_group_no = config_group_no

    @property
    def config_group_type(self):
        """Gets the config_group_type of this CloudDBConfigGroup.  # noqa: E501

        설정그룹유형  # noqa: E501

        :return: The config_group_type of this CloudDBConfigGroup.  # noqa: E501
        :rtype: str
        """
        return self._config_group_type

    @config_group_type.setter
    def config_group_type(self, config_group_type):
        """Sets the config_group_type of this CloudDBConfigGroup.

        설정그룹유형  # noqa: E501

        :param config_group_type: The config_group_type of this CloudDBConfigGroup.  # noqa: E501
        :type: str
        """

        self._config_group_type = config_group_type

    @property
    def config_group_name(self):
        """Gets the config_group_name of this CloudDBConfigGroup.  # noqa: E501

        설정그룹이름  # noqa: E501

        :return: The config_group_name of this CloudDBConfigGroup.  # noqa: E501
        :rtype: str
        """
        return self._config_group_name

    @config_group_name.setter
    def config_group_name(self, config_group_name):
        """Sets the config_group_name of this CloudDBConfigGroup.

        설정그룹이름  # noqa: E501

        :param config_group_name: The config_group_name of this CloudDBConfigGroup.  # noqa: E501
        :type: str
        """

        self._config_group_name = config_group_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CloudDBConfigGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
