# coding: utf-8

"""
    clouddb

    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetBackupListRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cloud_db_instance_no': 'str',
        'database_name': 'str',
        'backup_type_code': 'str'
    }

    attribute_map = {
        'cloud_db_instance_no': 'cloudDBInstanceNo',
        'database_name': 'databaseName',
        'backup_type_code': 'backupTypeCode'
    }

    def __init__(self, cloud_db_instance_no=None, database_name=None, backup_type_code=None):  # noqa: E501
        """GetBackupListRequest - a model defined in Swagger"""  # noqa: E501

        self._cloud_db_instance_no = None
        self._database_name = None
        self._backup_type_code = None
        self.discriminator = None

        self.cloud_db_instance_no = cloud_db_instance_no
        if database_name is not None:
            self.database_name = database_name
        if backup_type_code is not None:
            self.backup_type_code = backup_type_code

    @property
    def cloud_db_instance_no(self):
        """Gets the cloud_db_instance_no of this GetBackupListRequest.  # noqa: E501

        클라우드DB인스턴스번호  # noqa: E501

        :return: The cloud_db_instance_no of this GetBackupListRequest.  # noqa: E501
        :rtype: str
        """
        return self._cloud_db_instance_no

    @cloud_db_instance_no.setter
    def cloud_db_instance_no(self, cloud_db_instance_no):
        """Sets the cloud_db_instance_no of this GetBackupListRequest.

        클라우드DB인스턴스번호  # noqa: E501

        :param cloud_db_instance_no: The cloud_db_instance_no of this GetBackupListRequest.  # noqa: E501
        :type: str
        """
        if cloud_db_instance_no is None:
            raise ValueError("Invalid value for `cloud_db_instance_no`, must not be `None`")  # noqa: E501

        self._cloud_db_instance_no = cloud_db_instance_no

    @property
    def database_name(self):
        """Gets the database_name of this GetBackupListRequest.  # noqa: E501

        데이터베이스이름  # noqa: E501

        :return: The database_name of this GetBackupListRequest.  # noqa: E501
        :rtype: str
        """
        return self._database_name

    @database_name.setter
    def database_name(self, database_name):
        """Sets the database_name of this GetBackupListRequest.

        데이터베이스이름  # noqa: E501

        :param database_name: The database_name of this GetBackupListRequest.  # noqa: E501
        :type: str
        """

        self._database_name = database_name

    @property
    def backup_type_code(self):
        """Gets the backup_type_code of this GetBackupListRequest.  # noqa: E501

        백업유형코드  # noqa: E501

        :return: The backup_type_code of this GetBackupListRequest.  # noqa: E501
        :rtype: str
        """
        return self._backup_type_code

    @backup_type_code.setter
    def backup_type_code(self, backup_type_code):
        """Sets the backup_type_code of this GetBackupListRequest.

        백업유형코드  # noqa: E501

        :param backup_type_code: The backup_type_code of this GetBackupListRequest.  # noqa: E501
        :type: str
        """

        self._backup_type_code = backup_type_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetBackupListRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
