# coding: utf-8

"""
    clouddb

    OpenAPI spec version: 2018-06-21T02:28:05Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetCloudDBConfigGroupListRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'db_kind_code': 'str'
    }

    attribute_map = {
        'db_kind_code': 'dbKindCode'
    }

    def __init__(self, db_kind_code=None):  # noqa: E501
        """GetCloudDBConfigGroupListRequest - a model defined in Swagger"""  # noqa: E501

        self._db_kind_code = None
        self.discriminator = None

        self.db_kind_code = db_kind_code

    @property
    def db_kind_code(self):
        """Gets the db_kind_code of this GetCloudDBConfigGroupListRequest.  # noqa: E501

        DB유형코드  # noqa: E501

        :return: The db_kind_code of this GetCloudDBConfigGroupListRequest.  # noqa: E501
        :rtype: str
        """
        return self._db_kind_code

    @db_kind_code.setter
    def db_kind_code(self, db_kind_code):
        """Sets the db_kind_code of this GetCloudDBConfigGroupListRequest.

        DB유형코드  # noqa: E501

        :param db_kind_code: The db_kind_code of this GetCloudDBConfigGroupListRequest.  # noqa: E501
        :type: str
        """
        if db_kind_code is None:
            raise ValueError("Invalid value for `db_kind_code`, must not be `None`")  # noqa: E501

        self._db_kind_code = db_kind_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetCloudDBConfigGroupListRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
