# coding: utf-8

"""
    clouddb

    OpenAPI spec version: 2018-06-21T02:28:05Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RebootCloudDBServerInstanceRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cloud_db_server_instance_no': 'str',
        'is_with_failover': 'bool',
        'is_reboot_now': 'bool',
        'reboot_time': 'str'
    }

    attribute_map = {
        'cloud_db_server_instance_no': 'cloudDBServerInstanceNo',
        'is_with_failover': 'isWithFailover',
        'is_reboot_now': 'isRebootNow',
        'reboot_time': 'rebootTime'
    }

    def __init__(self, cloud_db_server_instance_no=None, is_with_failover=None, is_reboot_now=None, reboot_time=None):  # noqa: E501
        """RebootCloudDBServerInstanceRequest - a model defined in Swagger"""  # noqa: E501

        self._cloud_db_server_instance_no = None
        self._is_with_failover = None
        self._is_reboot_now = None
        self._reboot_time = None
        self.discriminator = None

        self.cloud_db_server_instance_no = cloud_db_server_instance_no
        if is_with_failover is not None:
            self.is_with_failover = is_with_failover
        if is_reboot_now is not None:
            self.is_reboot_now = is_reboot_now
        if reboot_time is not None:
            self.reboot_time = reboot_time

    @property
    def cloud_db_server_instance_no(self):
        """Gets the cloud_db_server_instance_no of this RebootCloudDBServerInstanceRequest.  # noqa: E501

        CloudDB서버인스턴스번호  # noqa: E501

        :return: The cloud_db_server_instance_no of this RebootCloudDBServerInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._cloud_db_server_instance_no

    @cloud_db_server_instance_no.setter
    def cloud_db_server_instance_no(self, cloud_db_server_instance_no):
        """Sets the cloud_db_server_instance_no of this RebootCloudDBServerInstanceRequest.

        CloudDB서버인스턴스번호  # noqa: E501

        :param cloud_db_server_instance_no: The cloud_db_server_instance_no of this RebootCloudDBServerInstanceRequest.  # noqa: E501
        :type: str
        """
        if cloud_db_server_instance_no is None:
            raise ValueError("Invalid value for `cloud_db_server_instance_no`, must not be `None`")  # noqa: E501

        self._cloud_db_server_instance_no = cloud_db_server_instance_no

    @property
    def is_with_failover(self):
        """Gets the is_with_failover of this RebootCloudDBServerInstanceRequest.  # noqa: E501

        Failover여부  # noqa: E501

        :return: The is_with_failover of this RebootCloudDBServerInstanceRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_with_failover

    @is_with_failover.setter
    def is_with_failover(self, is_with_failover):
        """Sets the is_with_failover of this RebootCloudDBServerInstanceRequest.

        Failover여부  # noqa: E501

        :param is_with_failover: The is_with_failover of this RebootCloudDBServerInstanceRequest.  # noqa: E501
        :type: bool
        """

        self._is_with_failover = is_with_failover

    @property
    def is_reboot_now(self):
        """Gets the is_reboot_now of this RebootCloudDBServerInstanceRequest.  # noqa: E501

        지금재부팅여부  # noqa: E501

        :return: The is_reboot_now of this RebootCloudDBServerInstanceRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_reboot_now

    @is_reboot_now.setter
    def is_reboot_now(self, is_reboot_now):
        """Sets the is_reboot_now of this RebootCloudDBServerInstanceRequest.

        지금재부팅여부  # noqa: E501

        :param is_reboot_now: The is_reboot_now of this RebootCloudDBServerInstanceRequest.  # noqa: E501
        :type: bool
        """

        self._is_reboot_now = is_reboot_now

    @property
    def reboot_time(self):
        """Gets the reboot_time of this RebootCloudDBServerInstanceRequest.  # noqa: E501

        예약재부팅시간  # noqa: E501

        :return: The reboot_time of this RebootCloudDBServerInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._reboot_time

    @reboot_time.setter
    def reboot_time(self, reboot_time):
        """Sets the reboot_time of this RebootCloudDBServerInstanceRequest.

        예약재부팅시간  # noqa: E501

        :param reboot_time: The reboot_time of this RebootCloudDBServerInstanceRequest.  # noqa: E501
        :type: str
        """

        self._reboot_time = reboot_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RebootCloudDBServerInstanceRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
