# coding: utf-8

"""
    monitoring

    OpenAPI spec version: 2020-05-22T05:53:06Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ncloud_monitoring.model.metric_data import MetricData  # noqa: F401,E501


class MetricStatistic(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'instance_no': 'str',
        'metric_data_list': 'list[MetricData]'
    }

    attribute_map = {
        'instance_no': 'instanceNo',
        'metric_data_list': 'metricDataList'
    }

    def __init__(self, instance_no=None, metric_data_list=None):  # noqa: E501
        """MetricStatistic - a model defined in Swagger"""  # noqa: E501

        self._instance_no = None
        self._metric_data_list = None
        self.discriminator = None

        if instance_no is not None:
            self.instance_no = instance_no
        if metric_data_list is not None:
            self.metric_data_list = metric_data_list

    @property
    def instance_no(self):
        """Gets the instance_no of this MetricStatistic.  # noqa: E501


        :return: The instance_no of this MetricStatistic.  # noqa: E501
        :rtype: str
        """
        return self._instance_no

    @instance_no.setter
    def instance_no(self, instance_no):
        """Sets the instance_no of this MetricStatistic.


        :param instance_no: The instance_no of this MetricStatistic.  # noqa: E501
        :type: str
        """

        self._instance_no = instance_no

    @property
    def metric_data_list(self):
        """Gets the metric_data_list of this MetricStatistic.  # noqa: E501


        :return: The metric_data_list of this MetricStatistic.  # noqa: E501
        :rtype: list[MetricData]
        """
        return self._metric_data_list

    @metric_data_list.setter
    def metric_data_list(self, metric_data_list):
        """Sets the metric_data_list of this MetricStatistic.


        :param metric_data_list: The metric_data_list of this MetricStatistic.  # noqa: E501
        :type: list[MetricData]
        """

        self._metric_data_list = metric_data_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetricStatistic):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
