# coding: utf-8

"""
    loadbalancer

    OpenAPI spec version: 2018-06-21T02:19:18Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AddLoadBalancerSslCertificateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'private_key': 'str',
        'public_key_certificate': 'str',
        'certificate_chain': 'str'
    }

    attribute_map = {
        'private_key': 'privateKey',
        'public_key_certificate': 'publicKeyCertificate',
        'certificate_chain': 'certificateChain'
    }

    def __init__(self, private_key=None, public_key_certificate=None, certificate_chain=None):  # noqa: E501
        """AddLoadBalancerSslCertificateRequest - a model defined in Swagger"""  # noqa: E501

        self._private_key = None
        self._public_key_certificate = None
        self._certificate_chain = None
        self.discriminator = None

        self.private_key = private_key
        self.public_key_certificate = public_key_certificate
        if certificate_chain is not None:
            self.certificate_chain = certificate_chain

    @property
    def private_key(self):
        """Gets the private_key of this AddLoadBalancerSslCertificateRequest.  # noqa: E501

        비밀키  # noqa: E501

        :return: The private_key of this AddLoadBalancerSslCertificateRequest.  # noqa: E501
        :rtype: str
        """
        return self._private_key

    @private_key.setter
    def private_key(self, private_key):
        """Sets the private_key of this AddLoadBalancerSslCertificateRequest.

        비밀키  # noqa: E501

        :param private_key: The private_key of this AddLoadBalancerSslCertificateRequest.  # noqa: E501
        :type: str
        """
        if private_key is None:
            raise ValueError("Invalid value for `private_key`, must not be `None`")  # noqa: E501

        self._private_key = private_key

    @property
    def public_key_certificate(self):
        """Gets the public_key_certificate of this AddLoadBalancerSslCertificateRequest.  # noqa: E501

        공개키인증서  # noqa: E501

        :return: The public_key_certificate of this AddLoadBalancerSslCertificateRequest.  # noqa: E501
        :rtype: str
        """
        return self._public_key_certificate

    @public_key_certificate.setter
    def public_key_certificate(self, public_key_certificate):
        """Sets the public_key_certificate of this AddLoadBalancerSslCertificateRequest.

        공개키인증서  # noqa: E501

        :param public_key_certificate: The public_key_certificate of this AddLoadBalancerSslCertificateRequest.  # noqa: E501
        :type: str
        """
        if public_key_certificate is None:
            raise ValueError("Invalid value for `public_key_certificate`, must not be `None`")  # noqa: E501

        self._public_key_certificate = public_key_certificate

    @property
    def certificate_chain(self):
        """Gets the certificate_chain of this AddLoadBalancerSslCertificateRequest.  # noqa: E501

        체인인증서  # noqa: E501

        :return: The certificate_chain of this AddLoadBalancerSslCertificateRequest.  # noqa: E501
        :rtype: str
        """
        return self._certificate_chain

    @certificate_chain.setter
    def certificate_chain(self, certificate_chain):
        """Sets the certificate_chain of this AddLoadBalancerSslCertificateRequest.

        체인인증서  # noqa: E501

        :param certificate_chain: The certificate_chain of this AddLoadBalancerSslCertificateRequest.  # noqa: E501
        :type: str
        """

        self._certificate_chain = certificate_chain

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddLoadBalancerSslCertificateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
