# coding: utf-8

"""
    vloadbalancer

    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetLoadBalancerInstanceListRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'region_code': 'str',
        'load_balancer_instance_no_list': 'list[str]',
        'load_balancer_network_type_code': 'str',
        'load_balancer_type_code': 'str',
        'page_no': 'int',
        'page_size': 'int',
        'sort_list': 'str',
        'vpc_no': 'str'
    }

    attribute_map = {
        'region_code': 'regionCode',
        'load_balancer_instance_no_list': 'loadBalancerInstanceNoList',
        'load_balancer_network_type_code': 'loadBalancerNetworkTypeCode',
        'load_balancer_type_code': 'loadBalancerTypeCode',
        'page_no': 'pageNo',
        'page_size': 'pageSize',
        'sort_list': 'sortList',
        'vpc_no': 'vpcNo'
    }

    def __init__(self, region_code=None, load_balancer_instance_no_list=None, load_balancer_network_type_code=None, load_balancer_type_code=None, page_no=None, page_size=None, sort_list=None, vpc_no=None):  # noqa: E501
        """GetLoadBalancerInstanceListRequest - a model defined in Swagger"""  # noqa: E501

        self._region_code = None
        self._load_balancer_instance_no_list = None
        self._load_balancer_network_type_code = None
        self._load_balancer_type_code = None
        self._page_no = None
        self._page_size = None
        self._sort_list = None
        self._vpc_no = None
        self.discriminator = None

        if region_code is not None:
            self.region_code = region_code
        if load_balancer_instance_no_list is not None:
            self.load_balancer_instance_no_list = load_balancer_instance_no_list
        if load_balancer_network_type_code is not None:
            self.load_balancer_network_type_code = load_balancer_network_type_code
        if load_balancer_type_code is not None:
            self.load_balancer_type_code = load_balancer_type_code
        if page_no is not None:
            self.page_no = page_no
        if page_size is not None:
            self.page_size = page_size
        if sort_list is not None:
            self.sort_list = sort_list
        if vpc_no is not None:
            self.vpc_no = vpc_no

    @property
    def region_code(self):
        """Gets the region_code of this GetLoadBalancerInstanceListRequest.  # noqa: E501

        REGION코드  # noqa: E501

        :return: The region_code of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :rtype: str
        """
        return self._region_code

    @region_code.setter
    def region_code(self, region_code):
        """Sets the region_code of this GetLoadBalancerInstanceListRequest.

        REGION코드  # noqa: E501

        :param region_code: The region_code of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :type: str
        """

        self._region_code = region_code

    @property
    def load_balancer_instance_no_list(self):
        """Gets the load_balancer_instance_no_list of this GetLoadBalancerInstanceListRequest.  # noqa: E501

        로드밸런서인스턴스번호리스트  # noqa: E501

        :return: The load_balancer_instance_no_list of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._load_balancer_instance_no_list

    @load_balancer_instance_no_list.setter
    def load_balancer_instance_no_list(self, load_balancer_instance_no_list):
        """Sets the load_balancer_instance_no_list of this GetLoadBalancerInstanceListRequest.

        로드밸런서인스턴스번호리스트  # noqa: E501

        :param load_balancer_instance_no_list: The load_balancer_instance_no_list of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :type: list[str]
        """

        self._load_balancer_instance_no_list = load_balancer_instance_no_list

    @property
    def load_balancer_network_type_code(self):
        """Gets the load_balancer_network_type_code of this GetLoadBalancerInstanceListRequest.  # noqa: E501

        로드밸런서네트워크유형코드  # noqa: E501

        :return: The load_balancer_network_type_code of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :rtype: str
        """
        return self._load_balancer_network_type_code

    @load_balancer_network_type_code.setter
    def load_balancer_network_type_code(self, load_balancer_network_type_code):
        """Sets the load_balancer_network_type_code of this GetLoadBalancerInstanceListRequest.

        로드밸런서네트워크유형코드  # noqa: E501

        :param load_balancer_network_type_code: The load_balancer_network_type_code of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :type: str
        """

        self._load_balancer_network_type_code = load_balancer_network_type_code

    @property
    def load_balancer_type_code(self):
        """Gets the load_balancer_type_code of this GetLoadBalancerInstanceListRequest.  # noqa: E501

        로드밸런서유형코드  # noqa: E501

        :return: The load_balancer_type_code of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :rtype: str
        """
        return self._load_balancer_type_code

    @load_balancer_type_code.setter
    def load_balancer_type_code(self, load_balancer_type_code):
        """Sets the load_balancer_type_code of this GetLoadBalancerInstanceListRequest.

        로드밸런서유형코드  # noqa: E501

        :param load_balancer_type_code: The load_balancer_type_code of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :type: str
        """

        self._load_balancer_type_code = load_balancer_type_code

    @property
    def page_no(self):
        """Gets the page_no of this GetLoadBalancerInstanceListRequest.  # noqa: E501

        페이지번호  # noqa: E501

        :return: The page_no of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :rtype: int
        """
        return self._page_no

    @page_no.setter
    def page_no(self, page_no):
        """Sets the page_no of this GetLoadBalancerInstanceListRequest.

        페이지번호  # noqa: E501

        :param page_no: The page_no of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :type: int
        """

        self._page_no = page_no

    @property
    def page_size(self):
        """Gets the page_size of this GetLoadBalancerInstanceListRequest.  # noqa: E501

        페이지사이즈  # noqa: E501

        :return: The page_size of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this GetLoadBalancerInstanceListRequest.

        페이지사이즈  # noqa: E501

        :param page_size: The page_size of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def sort_list(self):
        """Gets the sort_list of this GetLoadBalancerInstanceListRequest.  # noqa: E501

        정렬리스트  # noqa: E501

        :return: The sort_list of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :rtype: str
        """
        return self._sort_list

    @sort_list.setter
    def sort_list(self, sort_list):
        """Sets the sort_list of this GetLoadBalancerInstanceListRequest.

        정렬리스트  # noqa: E501

        :param sort_list: The sort_list of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :type: str
        """

        self._sort_list = sort_list

    @property
    def vpc_no(self):
        """Gets the vpc_no of this GetLoadBalancerInstanceListRequest.  # noqa: E501

        VPC번호  # noqa: E501

        :return: The vpc_no of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :rtype: str
        """
        return self._vpc_no

    @vpc_no.setter
    def vpc_no(self, vpc_no):
        """Sets the vpc_no of this GetLoadBalancerInstanceListRequest.

        VPC번호  # noqa: E501

        :param vpc_no: The vpc_no of this GetLoadBalancerInstanceListRequest.  # noqa: E501
        :type: str
        """

        self._vpc_no = vpc_no

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetLoadBalancerInstanceListRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
