# coding: utf-8

"""
    vloadbalancer

    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ncloud_vloadbalancer.model.common_code import CommonCode  # noqa: F401,E501
from ncloud_vloadbalancer.model.redirection_action import RedirectionAction  # noqa: F401,E501
from ncloud_vloadbalancer.model.target_group_action import TargetGroupAction  # noqa: F401,E501


class LoadBalancerRuleAction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rule_action_type': 'CommonCode',
        'target_group_action': 'TargetGroupAction',
        'redirection_action': 'RedirectionAction'
    }

    attribute_map = {
        'rule_action_type': 'ruleActionType',
        'target_group_action': 'targetGroupAction',
        'redirection_action': 'redirectionAction'
    }

    def __init__(self, rule_action_type=None, target_group_action=None, redirection_action=None):  # noqa: E501
        """LoadBalancerRuleAction - a model defined in Swagger"""  # noqa: E501

        self._rule_action_type = None
        self._target_group_action = None
        self._redirection_action = None
        self.discriminator = None

        if rule_action_type is not None:
            self.rule_action_type = rule_action_type
        if target_group_action is not None:
            self.target_group_action = target_group_action
        if redirection_action is not None:
            self.redirection_action = redirection_action

    @property
    def rule_action_type(self):
        """Gets the rule_action_type of this LoadBalancerRuleAction.  # noqa: E501

        룰액션유형  # noqa: E501

        :return: The rule_action_type of this LoadBalancerRuleAction.  # noqa: E501
        :rtype: CommonCode
        """
        return self._rule_action_type

    @rule_action_type.setter
    def rule_action_type(self, rule_action_type):
        """Sets the rule_action_type of this LoadBalancerRuleAction.

        룰액션유형  # noqa: E501

        :param rule_action_type: The rule_action_type of this LoadBalancerRuleAction.  # noqa: E501
        :type: CommonCode
        """

        self._rule_action_type = rule_action_type

    @property
    def target_group_action(self):
        """Gets the target_group_action of this LoadBalancerRuleAction.  # noqa: E501

        타겟그룹액션  # noqa: E501

        :return: The target_group_action of this LoadBalancerRuleAction.  # noqa: E501
        :rtype: TargetGroupAction
        """
        return self._target_group_action

    @target_group_action.setter
    def target_group_action(self, target_group_action):
        """Sets the target_group_action of this LoadBalancerRuleAction.

        타겟그룹액션  # noqa: E501

        :param target_group_action: The target_group_action of this LoadBalancerRuleAction.  # noqa: E501
        :type: TargetGroupAction
        """

        self._target_group_action = target_group_action

    @property
    def redirection_action(self):
        """Gets the redirection_action of this LoadBalancerRuleAction.  # noqa: E501

        리다이렉션액션  # noqa: E501

        :return: The redirection_action of this LoadBalancerRuleAction.  # noqa: E501
        :rtype: RedirectionAction
        """
        return self._redirection_action

    @redirection_action.setter
    def redirection_action(self, redirection_action):
        """Sets the redirection_action of this LoadBalancerRuleAction.

        리다이렉션액션  # noqa: E501

        :param redirection_action: The redirection_action of this LoadBalancerRuleAction.  # noqa: E501
        :type: RedirectionAction
        """

        self._redirection_action = redirection_action

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoadBalancerRuleAction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
