# coding: utf-8

"""
    vserver

    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CreatePublicIpInstanceRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'region_code': 'str',
        'public_ip_description': 'str',
        'server_instance_no': 'str'
    }

    attribute_map = {
        'region_code': 'regionCode',
        'public_ip_description': 'publicIpDescription',
        'server_instance_no': 'serverInstanceNo'
    }

    def __init__(self, region_code=None, public_ip_description=None, server_instance_no=None):  # noqa: E501
        """CreatePublicIpInstanceRequest - a model defined in Swagger"""  # noqa: E501

        self._region_code = None
        self._public_ip_description = None
        self._server_instance_no = None
        self.discriminator = None

        if region_code is not None:
            self.region_code = region_code
        if public_ip_description is not None:
            self.public_ip_description = public_ip_description
        if server_instance_no is not None:
            self.server_instance_no = server_instance_no

    @property
    def region_code(self):
        """Gets the region_code of this CreatePublicIpInstanceRequest.  # noqa: E501

        REGION코드  # noqa: E501

        :return: The region_code of this CreatePublicIpInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._region_code

    @region_code.setter
    def region_code(self, region_code):
        """Sets the region_code of this CreatePublicIpInstanceRequest.

        REGION코드  # noqa: E501

        :param region_code: The region_code of this CreatePublicIpInstanceRequest.  # noqa: E501
        :type: str
        """

        self._region_code = region_code

    @property
    def public_ip_description(self):
        """Gets the public_ip_description of this CreatePublicIpInstanceRequest.  # noqa: E501

        공인IP설명  # noqa: E501

        :return: The public_ip_description of this CreatePublicIpInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._public_ip_description

    @public_ip_description.setter
    def public_ip_description(self, public_ip_description):
        """Sets the public_ip_description of this CreatePublicIpInstanceRequest.

        공인IP설명  # noqa: E501

        :param public_ip_description: The public_ip_description of this CreatePublicIpInstanceRequest.  # noqa: E501
        :type: str
        """

        self._public_ip_description = public_ip_description

    @property
    def server_instance_no(self):
        """Gets the server_instance_no of this CreatePublicIpInstanceRequest.  # noqa: E501

        서버인스턴스번호  # noqa: E501

        :return: The server_instance_no of this CreatePublicIpInstanceRequest.  # noqa: E501
        :rtype: str
        """
        return self._server_instance_no

    @server_instance_no.setter
    def server_instance_no(self, server_instance_no):
        """Sets the server_instance_no of this CreatePublicIpInstanceRequest.

        서버인스턴스번호  # noqa: E501

        :param server_instance_no: The server_instance_no of this CreatePublicIpInstanceRequest.  # noqa: E501
        :type: str
        """

        self._server_instance_no = server_instance_no

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreatePublicIpInstanceRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
