# coding: utf-8

"""
    vserver

    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ncloud_vserver.model.network_interface_parameter import NetworkInterfaceParameter  # noqa: F401,E501


class CreateServerInstancesRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'region_code': 'str',
        'server_product_code': 'str',
        'server_image_product_code': 'str',
        'member_server_image_instance_no': 'str',
        'server_name': 'str',
        'server_description': 'str',
        'login_key_name': 'str',
        'is_protect_server_termination': 'bool',
        'server_create_count': 'int',
        'server_create_start_no': 'int',
        'fee_system_type_code': 'str',
        'init_script_no': 'str',
        'vpc_no': 'str',
        'subnet_no': 'str',
        'network_interface_list': 'list[NetworkInterfaceParameter]',
        'placement_group_no': 'str',
        'is_encrypted_base_block_storage_volume': 'bool'
    }

    attribute_map = {
        'region_code': 'regionCode',
        'server_product_code': 'serverProductCode',
        'server_image_product_code': 'serverImageProductCode',
        'member_server_image_instance_no': 'memberServerImageInstanceNo',
        'server_name': 'serverName',
        'server_description': 'serverDescription',
        'login_key_name': 'loginKeyName',
        'is_protect_server_termination': 'isProtectServerTermination',
        'server_create_count': 'serverCreateCount',
        'server_create_start_no': 'serverCreateStartNo',
        'fee_system_type_code': 'feeSystemTypeCode',
        'init_script_no': 'initScriptNo',
        'vpc_no': 'vpcNo',
        'subnet_no': 'subnetNo',
        'network_interface_list': 'networkInterfaceList',
        'placement_group_no': 'placementGroupNo',
        'is_encrypted_base_block_storage_volume': 'isEncryptedBaseBlockStorageVolume'
    }

    def __init__(self, region_code=None, server_product_code=None, server_image_product_code=None, member_server_image_instance_no=None, server_name=None, server_description=None, login_key_name=None, is_protect_server_termination=None, server_create_count=None, server_create_start_no=None, fee_system_type_code=None, init_script_no=None, vpc_no=None, subnet_no=None, network_interface_list=None, placement_group_no=None, is_encrypted_base_block_storage_volume=None):  # noqa: E501
        """CreateServerInstancesRequest - a model defined in Swagger"""  # noqa: E501

        self._region_code = None
        self._server_product_code = None
        self._server_image_product_code = None
        self._member_server_image_instance_no = None
        self._server_name = None
        self._server_description = None
        self._login_key_name = None
        self._is_protect_server_termination = None
        self._server_create_count = None
        self._server_create_start_no = None
        self._fee_system_type_code = None
        self._init_script_no = None
        self._vpc_no = None
        self._subnet_no = None
        self._network_interface_list = None
        self._placement_group_no = None
        self._is_encrypted_base_block_storage_volume = None
        self.discriminator = None

        if region_code is not None:
            self.region_code = region_code
        if server_product_code is not None:
            self.server_product_code = server_product_code
        if server_image_product_code is not None:
            self.server_image_product_code = server_image_product_code
        if member_server_image_instance_no is not None:
            self.member_server_image_instance_no = member_server_image_instance_no
        if server_name is not None:
            self.server_name = server_name
        if server_description is not None:
            self.server_description = server_description
        if login_key_name is not None:
            self.login_key_name = login_key_name
        if is_protect_server_termination is not None:
            self.is_protect_server_termination = is_protect_server_termination
        if server_create_count is not None:
            self.server_create_count = server_create_count
        if server_create_start_no is not None:
            self.server_create_start_no = server_create_start_no
        if fee_system_type_code is not None:
            self.fee_system_type_code = fee_system_type_code
        if init_script_no is not None:
            self.init_script_no = init_script_no
        self.vpc_no = vpc_no
        self.subnet_no = subnet_no
        self.network_interface_list = network_interface_list
        if placement_group_no is not None:
            self.placement_group_no = placement_group_no
        if is_encrypted_base_block_storage_volume is not None:
            self.is_encrypted_base_block_storage_volume = is_encrypted_base_block_storage_volume

    @property
    def region_code(self):
        """Gets the region_code of this CreateServerInstancesRequest.  # noqa: E501

        REGION코드  # noqa: E501

        :return: The region_code of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._region_code

    @region_code.setter
    def region_code(self, region_code):
        """Sets the region_code of this CreateServerInstancesRequest.

        REGION코드  # noqa: E501

        :param region_code: The region_code of this CreateServerInstancesRequest.  # noqa: E501
        :type: str
        """

        self._region_code = region_code

    @property
    def server_product_code(self):
        """Gets the server_product_code of this CreateServerInstancesRequest.  # noqa: E501

        서버상품코드  # noqa: E501

        :return: The server_product_code of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._server_product_code

    @server_product_code.setter
    def server_product_code(self, server_product_code):
        """Sets the server_product_code of this CreateServerInstancesRequest.

        서버상품코드  # noqa: E501

        :param server_product_code: The server_product_code of this CreateServerInstancesRequest.  # noqa: E501
        :type: str
        """

        self._server_product_code = server_product_code

    @property
    def server_image_product_code(self):
        """Gets the server_image_product_code of this CreateServerInstancesRequest.  # noqa: E501

        서버이미지상품코드  # noqa: E501

        :return: The server_image_product_code of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._server_image_product_code

    @server_image_product_code.setter
    def server_image_product_code(self, server_image_product_code):
        """Sets the server_image_product_code of this CreateServerInstancesRequest.

        서버이미지상품코드  # noqa: E501

        :param server_image_product_code: The server_image_product_code of this CreateServerInstancesRequest.  # noqa: E501
        :type: str
        """

        self._server_image_product_code = server_image_product_code

    @property
    def member_server_image_instance_no(self):
        """Gets the member_server_image_instance_no of this CreateServerInstancesRequest.  # noqa: E501

        회원서버이미지인스턴스번호  # noqa: E501

        :return: The member_server_image_instance_no of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._member_server_image_instance_no

    @member_server_image_instance_no.setter
    def member_server_image_instance_no(self, member_server_image_instance_no):
        """Sets the member_server_image_instance_no of this CreateServerInstancesRequest.

        회원서버이미지인스턴스번호  # noqa: E501

        :param member_server_image_instance_no: The member_server_image_instance_no of this CreateServerInstancesRequest.  # noqa: E501
        :type: str
        """

        self._member_server_image_instance_no = member_server_image_instance_no

    @property
    def server_name(self):
        """Gets the server_name of this CreateServerInstancesRequest.  # noqa: E501

        서버이름  # noqa: E501

        :return: The server_name of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._server_name

    @server_name.setter
    def server_name(self, server_name):
        """Sets the server_name of this CreateServerInstancesRequest.

        서버이름  # noqa: E501

        :param server_name: The server_name of this CreateServerInstancesRequest.  # noqa: E501
        :type: str
        """

        self._server_name = server_name

    @property
    def server_description(self):
        """Gets the server_description of this CreateServerInstancesRequest.  # noqa: E501

        서버설명  # noqa: E501

        :return: The server_description of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._server_description

    @server_description.setter
    def server_description(self, server_description):
        """Sets the server_description of this CreateServerInstancesRequest.

        서버설명  # noqa: E501

        :param server_description: The server_description of this CreateServerInstancesRequest.  # noqa: E501
        :type: str
        """

        self._server_description = server_description

    @property
    def login_key_name(self):
        """Gets the login_key_name of this CreateServerInstancesRequest.  # noqa: E501

        로그인키이름  # noqa: E501

        :return: The login_key_name of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._login_key_name

    @login_key_name.setter
    def login_key_name(self, login_key_name):
        """Sets the login_key_name of this CreateServerInstancesRequest.

        로그인키이름  # noqa: E501

        :param login_key_name: The login_key_name of this CreateServerInstancesRequest.  # noqa: E501
        :type: str
        """

        self._login_key_name = login_key_name

    @property
    def is_protect_server_termination(self):
        """Gets the is_protect_server_termination of this CreateServerInstancesRequest.  # noqa: E501

        반납보호여부  # noqa: E501

        :return: The is_protect_server_termination of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_protect_server_termination

    @is_protect_server_termination.setter
    def is_protect_server_termination(self, is_protect_server_termination):
        """Sets the is_protect_server_termination of this CreateServerInstancesRequest.

        반납보호여부  # noqa: E501

        :param is_protect_server_termination: The is_protect_server_termination of this CreateServerInstancesRequest.  # noqa: E501
        :type: bool
        """

        self._is_protect_server_termination = is_protect_server_termination

    @property
    def server_create_count(self):
        """Gets the server_create_count of this CreateServerInstancesRequest.  # noqa: E501

        서버생성개수  # noqa: E501

        :return: The server_create_count of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: int
        """
        return self._server_create_count

    @server_create_count.setter
    def server_create_count(self, server_create_count):
        """Sets the server_create_count of this CreateServerInstancesRequest.

        서버생성개수  # noqa: E501

        :param server_create_count: The server_create_count of this CreateServerInstancesRequest.  # noqa: E501
        :type: int
        """

        self._server_create_count = server_create_count

    @property
    def server_create_start_no(self):
        """Gets the server_create_start_no of this CreateServerInstancesRequest.  # noqa: E501

        서버생성시작번호  # noqa: E501

        :return: The server_create_start_no of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: int
        """
        return self._server_create_start_no

    @server_create_start_no.setter
    def server_create_start_no(self, server_create_start_no):
        """Sets the server_create_start_no of this CreateServerInstancesRequest.

        서버생성시작번호  # noqa: E501

        :param server_create_start_no: The server_create_start_no of this CreateServerInstancesRequest.  # noqa: E501
        :type: int
        """

        self._server_create_start_no = server_create_start_no

    @property
    def fee_system_type_code(self):
        """Gets the fee_system_type_code of this CreateServerInstancesRequest.  # noqa: E501

        요금제유형코드  # noqa: E501

        :return: The fee_system_type_code of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._fee_system_type_code

    @fee_system_type_code.setter
    def fee_system_type_code(self, fee_system_type_code):
        """Sets the fee_system_type_code of this CreateServerInstancesRequest.

        요금제유형코드  # noqa: E501

        :param fee_system_type_code: The fee_system_type_code of this CreateServerInstancesRequest.  # noqa: E501
        :type: str
        """

        self._fee_system_type_code = fee_system_type_code

    @property
    def init_script_no(self):
        """Gets the init_script_no of this CreateServerInstancesRequest.  # noqa: E501

        초기화스크립트번호  # noqa: E501

        :return: The init_script_no of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._init_script_no

    @init_script_no.setter
    def init_script_no(self, init_script_no):
        """Sets the init_script_no of this CreateServerInstancesRequest.

        초기화스크립트번호  # noqa: E501

        :param init_script_no: The init_script_no of this CreateServerInstancesRequest.  # noqa: E501
        :type: str
        """

        self._init_script_no = init_script_no

    @property
    def vpc_no(self):
        """Gets the vpc_no of this CreateServerInstancesRequest.  # noqa: E501

        VPC번호  # noqa: E501

        :return: The vpc_no of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._vpc_no

    @vpc_no.setter
    def vpc_no(self, vpc_no):
        """Sets the vpc_no of this CreateServerInstancesRequest.

        VPC번호  # noqa: E501

        :param vpc_no: The vpc_no of this CreateServerInstancesRequest.  # noqa: E501
        :type: str
        """
        if vpc_no is None:
            raise ValueError("Invalid value for `vpc_no`, must not be `None`")  # noqa: E501

        self._vpc_no = vpc_no

    @property
    def subnet_no(self):
        """Gets the subnet_no of this CreateServerInstancesRequest.  # noqa: E501

        서브넷번호  # noqa: E501

        :return: The subnet_no of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._subnet_no

    @subnet_no.setter
    def subnet_no(self, subnet_no):
        """Sets the subnet_no of this CreateServerInstancesRequest.

        서브넷번호  # noqa: E501

        :param subnet_no: The subnet_no of this CreateServerInstancesRequest.  # noqa: E501
        :type: str
        """
        if subnet_no is None:
            raise ValueError("Invalid value for `subnet_no`, must not be `None`")  # noqa: E501

        self._subnet_no = subnet_no

    @property
    def network_interface_list(self):
        """Gets the network_interface_list of this CreateServerInstancesRequest.  # noqa: E501

        네트워크인터페이스리스트  # noqa: E501

        :return: The network_interface_list of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: list[NetworkInterfaceParameter]
        """
        return self._network_interface_list

    @network_interface_list.setter
    def network_interface_list(self, network_interface_list):
        """Sets the network_interface_list of this CreateServerInstancesRequest.

        네트워크인터페이스리스트  # noqa: E501

        :param network_interface_list: The network_interface_list of this CreateServerInstancesRequest.  # noqa: E501
        :type: list[NetworkInterfaceParameter]
        """
        if network_interface_list is None:
            raise ValueError("Invalid value for `network_interface_list`, must not be `None`")  # noqa: E501

        self._network_interface_list = network_interface_list

    @property
    def placement_group_no(self):
        """Gets the placement_group_no of this CreateServerInstancesRequest.  # noqa: E501

        물리배치그룹번호  # noqa: E501

        :return: The placement_group_no of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: str
        """
        return self._placement_group_no

    @placement_group_no.setter
    def placement_group_no(self, placement_group_no):
        """Sets the placement_group_no of this CreateServerInstancesRequest.

        물리배치그룹번호  # noqa: E501

        :param placement_group_no: The placement_group_no of this CreateServerInstancesRequest.  # noqa: E501
        :type: str
        """

        self._placement_group_no = placement_group_no

    @property
    def is_encrypted_base_block_storage_volume(self):
        """Gets the is_encrypted_base_block_storage_volume of this CreateServerInstancesRequest.  # noqa: E501

        기본블록스토리지볼륨암호화여부  # noqa: E501

        :return: The is_encrypted_base_block_storage_volume of this CreateServerInstancesRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_encrypted_base_block_storage_volume

    @is_encrypted_base_block_storage_volume.setter
    def is_encrypted_base_block_storage_volume(self, is_encrypted_base_block_storage_volume):
        """Sets the is_encrypted_base_block_storage_volume of this CreateServerInstancesRequest.

        기본블록스토리지볼륨암호화여부  # noqa: E501

        :param is_encrypted_base_block_storage_volume: The is_encrypted_base_block_storage_volume of this CreateServerInstancesRequest.  # noqa: E501
        :type: bool
        """

        self._is_encrypted_base_block_storage_volume = is_encrypted_base_block_storage_volume

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateServerInstancesRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
